apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:oa3bhzCrqhByCNmWHza6JUm275QWWWT30UzkRhymgbN41tHL3r4PTA==,iv:QhaDilr9MTrQsProA4DNRPSDyeWrdqXpMRSccwosv78=,tag:uXNjpAaVBuxCYJ/OU6fnfg==,type:str]
sops:
  age:
    - recipient: age1eytupcvu9e6ft9k0s7zt9ujvfqpqd998c9pj6urr7duyh6rtys3qk5zeyj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydGltNlpXYldkK1RPSjJz
        VFBaSDdGRnhDeDR5ZW9oTHlqeWh5Q3BLbGpjCmU5cmhBR2s1UUZBNElXTXRsWmVU
        cFJRREdyREZTZTVCcEtCMVc3RnVlNFUKLS0tIGNUcUZEb1J5RHFUcFZaTkRUUTdi
        V05HZ1B2d2ZhbTVkNTlGNjEwVUZsYmsKl0gk8NSv8iB3dnKdVGE7O5HBWD84zPcF
        MMM+zE8JY5Hxftb2Ai3YsNtUKVRkURVmy7ConwnZuThBJTHtd7PTPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T15:06:05Z"
  mac: ENC[AES256_GCM,data:oaGbT1yGQNmzs761pU6HyLj3Fxi7Eh6Hdc3acLpA9gD+Wrhe2b4WNJepxUVHW/iIvt7+UoCQOZsdnXe3Ikt/kmCyiQckHBXCRwcrMS9me2SgOm2tUwaUdrwN+C1UZgkpfpHD8SlFD03fqu3uLJyn//y8+yfN511BWSfHL3zWRZ4=,iv:rfXotruoZFdIlzkmpLcHmh41gqCrwEBt8trkUSUnaas=,tag:mbOjAMdyT3F+qveKnh9/uA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
