apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:X6zFVqUUdb1nhg==,iv:TjiHROQUHahj7kW0gw16vQ4UnaM4/T5x0d55EO5arf4=,tag:z83FPHJ16fmsXdFv3jfHQA==,type:str]
sops:
  age:
    - recipient: age1eytupcvu9e6ft9k0s7zt9ujvfqpqd998c9pj6urr7duyh6rtys3qk5zeyj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZHJ0LzFMWVNRQ1NwNUY0
        c29CRys0VE9TZUgrbFBWT0FRQjZaYlRzVngwCk9tNkxWaUtDQzNWMTY1RW5YZ1BU
        Zk9GQkc3ZkJMUisrSE9sWUhrZkQ5TlkKLS0tIFU1M2M1cnJCTDY0aVFHWlozVW1i
        aGpKYWp2dmRqNHRLZjBWSDdwc3VGTTAKb0iYRD6kwj82wVTfIWBuBZrD7ji/yXAA
        nqPHKQhlvfoVbbDA92gCdLkOQhekk+/DE7PILcbi41Qrt0HLvtJQOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T15:06:05Z"
  mac: ENC[AES256_GCM,data:cN7ZbQ7u3rNDG7Ql20mnqMCLkOI6Ru9MGsyJnVsi/sAALvumruTVBsHUGKgMZzHWpo/JNS9Zob1URizDVqQZivv5yM41fvVIhjlg8/7eOnBsP76e8BUDuP1GH5xFSxSm4r/VRvJ3hAiLirBQP/tpmFw1tlHCYYkki4fXaY0IyCs=,iv:evCQMImASpFH4Pig3UfVY2ZdwBVxEv64ci5JpLgsteU=,tag:YdLShRACDt6A6PwlhJfC6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
