apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:/+xgL+ziHHI6o8KwaVMEM48mDRWiH6ZFwj0pmTGercI=,iv:BDrHiq/ozvI/4tDB+gt+X+6nwV52fOJmIrJ7/iAV4OQ=,tag:yEuhzEgx4oKI2yuDLcv5HA==,type:str]
sops:
  age:
    - recipient: age1eytupcvu9e6ft9k0s7zt9ujvfqpqd998c9pj6urr7duyh6rtys3qk5zeyj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaTBwT2loeHBzWVlmY2ht
        dGI4eHQyc3RGaTlSaGVoYWl3SzNKWHZRMGpJCkxjY0dOSzJUR2xVQ016Rk54dktO
        NHVvbm1OZVBPdVZlSVVjbCt1UzR3YW8KLS0tIGVLUGs2bEVranJwZnNQWm5nK3NJ
        dUQ1K0w1dGpqYlppTHRNa3RJd1dhNmMK/1riyAUp+knKTqRyJCWr6ud3+zcEJUiG
        WU5ygAS1CFnQg31nCJ3kLKYx7LSCZJnwJxR+UR4Z1EnYe2DyPEZTSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T15:06:05Z"
  mac: ENC[AES256_GCM,data:BOKn/WYh7KpLHkRrbGgRJ9LbUYOhrKeUKZPnkLX4ZpxbLBObp5qb4quxGH7CU/qR8HMvSj/rAUkREFUz9B76bTeljy56k7bdpfE0yT6UVf8ptAE6MKwIgXrRZqCR+K5ebOd9TVCGHP84xoUCBAZdk6cQsSF+Z9uqdSVV7kCGWmg=,iv:PbII59QwF+PKYZTK0YWK9rP4Dxk5tTfVJsh/W/cpIZU=,tag:YmS2zo5EVZ2c37W3sqHJXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
