---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app direwolf-operator
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  upgrade:
    crds: CreateReplace
    force: true
  values: []
#    controllers:
#      direwolf_operator:
#        containers:
#          operator:
#            env:
#              WOLF_IMAGE: ghcr.io/games-on-whales/wolf:dev-moonlight-fixes
