apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LgFZbE1jMpALvFFM0AU/OrGkttyapQS/1ezg3UZGb/oUUfvB4678z9Lo/w7FhnoefctuFRNso9jIbqNeorbtA4d9wjmixb8nsnmo+88QngOHTqSYIfLAmQd3oZfh9dNtnqhW0KrTEpDsbAOirKic8tmvI4X9q2xC0vQZ8ikBkkj0V7oddsh/d7cr3NKWpRcTKNrnHtO+9rBOdEMFt2Oyi6aMPZ1CDcpgAKnGQuHQA+lXea/1,iv:sHoJcE3FR650q0U5uaMvblxBsIAO+BfYNn5n65st6rg=,tag:JTDnjcORLKmIRjbbRcvSPw==,type:str]
sops:
  age:
    - recipient: age1eytupcvu9e6ft9k0s7zt9ujvfqpqd998c9pj6urr7duyh6rtys3qk5zeyj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNXhybU5LaGJSTGRFeTN6
        VDNnZkprVU53aDN4SzM0aGpScmdWRkMwQXpnCmY5M0tYVEdBV3U5MGZqZ0N1UFY4
        RmE1cDJKMWtjQkNSbDZJRXp2Q1dXRFkKLS0tIHhESkM3SVJpWExXY0dybWdyOW0r
        QUZIb2NGZ1dQUFNmRm0rTzVNc2M1R2sKlmeAngJo2sNuk06zgl8ay72KpyE/fHeS
        ktXP24i1FEnSylNZTRHA6eAjyc8bemC/ac2Q9elA4XjFe2tiqGQftg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T15:06:05Z"
  mac: ENC[AES256_GCM,data:cPn0Deug8NK6R1wMd6FjAniXWSGfcexvpI1on5uCVCgfN04x+54XR2ObXLIHVDajJZquymAMc+IrPZ1W6EM0ZA4Uig3aJ8e74HnLGaf4ptFyWh+W/k8TbhZfXQAgKwioSMwdXTZY8KNGrk439X0THN8Oatq/GQhsA5ivd1MdSVo=,iv:k1sSzIPmx6+JJZV3NBEqnE0nxYGyXSKvExRacR5EG3Y=,tag:ucOkv3vH/QVGEKSnnljUPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
