apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Tr033NxcHdFtnReWmFMLFPAiHGCiJ807W76DSthHaXxGMPyg/IlYjg==,iv:6IgDTPDj9fCYvo5wYdVdCA2NkSG+8mW6NU97DsP5LxA=,tag:g+uPDz4TLMA9+1lt1tae/Q==,type:str]
sops:
  age:
    - recipient: age1eytupcvu9e6ft9k0s7zt9ujvfqpqd998c9pj6urr7duyh6rtys3qk5zeyj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd1JrbHQ0K21UazhQdnRW
        VWVPQkJ5SGpCaFdvcHQ3S0NVaDFVa1dPeFJZCkF5SVhoVFlwRUU3SmpQZG92ay8z
        TzViTTdVYkplWEVKS2R2MXE0SjhRUmcKLS0tIEsyVGlMNi8zcVhHNDd4bjYxMy9h
        NkNxSjdtSW5FM3g5NDc3N041b1dNYncK4KRD1T6AYPHTPFM9TXu+BNLdbRAKS26B
        NtEqkYYLELlh3wK2r8mXsWDyFlM3LxyS8Z/gzH0/9qKLQhALUhDy1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T15:06:05Z"
  mac: ENC[AES256_GCM,data:RREW64EvdLuEbEk0BiFrO1YgglGoTsJtFHAgOtPv5hACWIeJi5YcU+g3JqBm+hSAClME54cO8dXK/TT9Ks/wCZMpYMyB6EzUVOsvWGumPW2ljbGNKuuzWSMIgW/bQnmOEAQ0b2qfWv1UpDmoViJjcdhIDPO0gO53UoB5C7nD5K8=,iv:68fwOXwIWXyYFiI7gEM3Wpql56Fk6ixpaSSqJNMP/QA=,tag:241L8ctj2eaan4gzp5WXDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
