---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-oidc"
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: "${APP}-oidc"
  data:
    - secretKey: client-secret
      remoteRef:
        key: "${VAULT_PREFIX}/${APP}"
        property: client-secret
    - secretKey: client-id
      remoteRef:
        key: "${VAULT_PREFIX}/${APP}"
        property: client-id
